<div class="threelinkWrap" id="accordion" data-mage-init='{
        
        "accordionjs":{}

        }'>



    <div class="threelinkBox">
        <div data-role="collapsible">
            <div data-role="trigger">
                <h2 class="threelinkTitle">About Nintendove</h2>
            </div>
        </div>
        <div data-role="content">
            <ul>
                <li><a>Company info</a></li>
                <li><a>Careers</a></li>
                <li><a>CSR Report</a></li>
                <li><a>Sitemap</a></li>
            </ul>
        </div>
    </div>

    <div class="threelinkBox">
        <div data-role="collapsible">
            <div data-role="trigger">
                <h2 class="threelinkTitle">Store Support</h2>
            </div>
        </div>
        <div data-role="content">
            <ul>
                <li><a>Order Status</a></li>
                <li><a>Shipping & Processing</a></li>
                <li><a>Returns & Exchanges</a></li>
                <li><a>Shipping & Processing</a></li>
                <li><a>Returns & Exchanges</a></li>
                <li><a>FAQ</a></li>
            </ul>
        </div>
    </div>

    <div class="threelinkBox">
        <div data-role="collapsible">
            <div data-role="trigger">
                <h2 class="threelinkTitle">Product Information</h2>
            </div>
        </div>
        <div data-role="content">
            <ul>
                <li><a>Product Support</a></li>
                <li><a>Repair Help</a></li>
                <li><a>Product Warranty</a></li>
                <li><a>Product Support</a></li>
                <li><a>Repair Help</a></li>
                <li><a>Product Warranty</a></li>
            </ul>
        </div>
    </div>
</div>